def header():
    return \
        "// ------------------------------------------\n" \
        "// Generated by Transwarp\n"                     \
        "//\n"                                            \
        "// THIS FILE IS AUTOMATICALLY GENERATED.\n"      \
        "// DO NOT EDIT. ALL CHANGES WILL BE LOST.\n"     \
        "// ------------------------------------------"
