import re
import json

from base64 import b64decode

from web.lib.gcodemeta import GCodeMeta


re_slicer = re.compile("^; generated by (\S+) (\S+) on (.+)")
re_slicer_utc = re.compile("(\S+) at (\S+) UTC")
re_thumb_begin = re.compile(b"thumbnail_JPG begin (\d+)x(\d+) (\d+)")
re_thumb_end = re.compile(b"thumbnail_JPG end")


class GCodeMetaPrusaSlicer(GCodeMeta):

    def detect_first_line(self, line):
        return b"generated by PrusaSlicer" in line

    @staticmethod
    def parse_prop(val):
        try:
            return json.loads(val)
        except json.decoder.JSONDecodeError:
            return val

    def _parse_slicer(self, line):
        m = re_slicer.match(line)
        res = {}

        slicer, version, tail = m.groups()

        res["__slicer_name"] = slicer
        res["__slicer_version"] = version

        if m := re_slicer_utc.match(tail):
            res["__slicer_date"] = f"{m.group(1)}_{m.group(2)}_UTC"

        return res

    def _parse_props(self, data, prefix=""):
        if data.startswith(b"; generated by "):
            res = self._parse_slicer(data[:1024].splitlines()[0].decode())
        else:
            res = {}

        thumbs = []
        thumb = []
        thumb_size = None

        for line in data.splitlines():
            if not line.startswith(b"; "):
                continue

            line = line.removeprefix(b"; ").strip()
            if not line:
                continue

            if b" = " in line:
                key, value = line.removeprefix(b"; ").decode().split(" = ", 1)
                key = key.lower().translate(str.maketrans(" ", "_", "[]()"))

                res[prefix + key] = self.parse_prop(value.strip())
            elif m := re_thumb_begin.match(line):
                thumb = []
                thumb_size = [int(m.group(1)), int(m.group(2))]
            elif m := re_thumb_end.match(line):
                thumbs.append((thumb_size, b64decode("".join(thumb))))
                thumb = []
            else:
                thumb.append(line.decode())

        if not thumbs:
            return res

        res["__thumbs"] = []
        for t in thumbs:
            res["__thumbs"].append({
                "width": t[0][0],
                "height": t[0][1],
                "data": t[1],
            })

        return res

    def load_props(self, fd):
        headsize = 32 * 1024
        tailsize = 32 * 1024

        fd.seek(0, 2)
        fsize = fd.tell()

        if fsize > (headsize + tailsize):
            fd.seek(-tailsize, 2)
            tail = fd.read(tailsize)
            fd.seek(0)
            head = fd.read(headsize)
            return {
                **self._parse_props(head, prefix="_"),
                **self._parse_props(tail),
            }
        else:
            fd.seek(0)
            return self._parse_props(fd.read())
