from web.lib.gcodemeta import GCodeMeta

class GCodeMetaPrusaSlicer(GCodeMeta):

    def detect_first_line(self, line):
        return b"generated by PrusaSlicer" in line

    def _parse_props(self, data, prefix=""):
        res = {}

        for line in data.splitlines():
            if not line.startswith(b"; "):
                continue

            line = line.removeprefix(b"; ").strip()
            if not line:
                continue

            if b" = " not in line:
                continue

            key, value = line.removeprefix(b"; ").decode().split(" = ", 1)
            key = key.lower().translate(str.maketrans(" ", "_", "[]()"))

            res[prefix + key] = value.strip()

        return res

    def load_props(self, fd):
        headsize = 32 * 1024
        tailsize = 32 * 1024

        fd.seek(0, 2)
        fsize = fd.tell()

        if fsize > (headsize + tailsize):
            fd.seek(-tailsize, 2)
            tail = fd.read(tailsize)
            fd.seek(0)
            head = fd.read(headsize)
            return {
                **self._parse_props(head, prefix="_"),
                **self._parse_props(tail),
            }
        else:
            fd.seek(0)
            return self._parse_props(fd.read())
