from web.lib.gcodemeta import GCodeMeta

class GCodeMetaPrusaSlicer(GCodeMeta):

    def detect_first_line(self, line):
        return b"generated by PrusaSlicer" in line

    def load_props(self, fd):
        rsize = 128 * 1024
        fd.seek(0, 2)
        fsize = fd.tell()
        size = min(fsize, rsize)
        fd.seek(-size, 2)
        lines = fd.read(size).splitlines()

        res = {}
        for line in lines:
            if not line.startswith(b"; "):
                continue

            line = line.removeprefix(b"; ").strip()
            if not line:
                continue

            if b" = " not in line:
                continue

            key, value = line.removeprefix(b"; ").decode().split(" = ", 1)
            res[key] = value

        return res
